#!/bin/bash
# Build script for Cactus
# Assembler: MADS (Mad Assembler)

cd "$(dirname "$0")"

mkdir -p bin

# Generate build timestamp
STAMP=$(date +"%d.%m.%Y %H:%M")
MSG="Cactus b01 $STAMP"
LEN=${#MSG}
COL=$(( (80 - LEN) / 2 ))

echo "; Auto-generated by build.sh - do not edit manually" > src/build_stamp.asm
echo "msg_welcome     dta c'$MSG',0" >> src/build_stamp.asm
echo "msg_welcome_col = $COL" >> src/build_stamp.asm

echo "Assembling Cactus..."
./mads.exe src/browser.asm -o:bin/cactus.xex -l:bin/cactus.lab -t:bin/cactus.lst

if [ $? -eq 0 ]; then
    echo "Build successful: bin/cactus.xex"
    ls -la bin/cactus.xex
else
    echo "Build FAILED!"
    exit 1
fi
